### ISSUE TITLE
Duplicate question 

### ISSUE THREAD

**Issue by hiksea** [NguyenTungSk2004/baotrihejthong#3]
![image](https://github.com/NguyenTungSk2004/baotrihethong/assets/105586419/152786e3-7112-470d-8ec9-d6f529bc82f1)
Your question have a lot of duplicate question, here are some example.Pls remove it, it waste my time a lot

**Comment by NguyenTungSk2004** [comment]
Pls don't make stupid cmts :)

**Comment by NguyenTungSk2004** [comment]
I will delete those questions in the future. Ok man :)
